# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "docker" do |docker|
    docker.vm.box = "Ubuntu_Server_20_04_LTS"
    docker.vm.hostname = "docker.mario.lab"
    docker.vm.box_check_update = true
    docker.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    docker.vm.synced_folder "containers/", "/synced"
    docker.vm.provider :virtualbox do |vbox|
      vbox.customize ["modifyvm", :id, "--memory", "3072"]
    end
    docker.vm.provision "docker" do |d|
      d.build_image "/synced/nginx/",
        args: "-t load_balancer"
      
      d.build_image "/synced/app/",
        args: "-t node_app"
      
      d.run "load_balancer",
        image: "load_balancer",
        args: "--network host"

      d.run "node_app_a",
        image: "node_app",
        args: "--publish 8081:3000"
      
      d.run "node_app_b",
        image: "node_app",
        args: "--publish 8082:3000"
    end
  end
end
