# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false

  config.vm.define "docker" do |docker|
    docker.vm.box = "opensuse/Leap-15.2.x86_64"
    
    docker.vm.provider :virtualbox do |docker_vbox|
      docker_vbox.customize ["modifyvm", :id, "--memory", "2048"]
    end

    docker.vm.hostname = "docker.mario.lab"
    docker.vm.network "private_network",
      name: "vboxnet0",
      ip: "10.1.1.3",
      # netmask: "24", if you leave this line the mask get's set to 32
      hostname: true

    docker.vm.network "forwarded_port",
      guest: 8080, 
      host: 8080, 
      auto_correct: true
    
    docker.vm.provision "shell", path: "provision_docker_box.sh"
  end

  config.vm.define "ansible" do |ansible|
    ansible.vm.box = "alpine_box"
    
    ansible.vm.provider :virtualbox do |ans_vbox|
      ans_vbox.customize ["modifyvm", :id, "--memory", "512", '--cpuexecutioncap', '40']
    end
    
    ansible.vm.hostname = "ansible.mario.lab"
    ansible.vm.network "private_network",
      name: "vboxnet0",
      ip: "10.1.1.2",
      netmask: "24",
      hostname: true

    ansible.vm.synced_folder "sync", "/sync"
    ansible.vm.provision "shell", path: "provision_ansible_box.sh"
  end

end
