apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-demo
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: secrets-demo
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: secrets-demo
    spec:
      containers:
      - name: secrets-demo-container
        image: shekeriev/environment
        env:
        - name: CONT_ENV_VAR
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: secret
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: secrets-demo-svc
  labels:
    app: secrets-demo
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30005
    protocol: TCP
  selector:
    app: secrets-demo
