# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false

  config.vm.define "web" do |web|
    web.vm.box="Ubuntu_Server_20_04_LTS"
    web.vm.hostname = "web.mario.lab"
    web.vm.network "private_network", ip: "192.168.89.100"
    web.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    web.vm.synced_folder "application/web/", "/synced"
    web.vm.provision "shell", path: "web.sh"
  end

  config.vm.define "db" do |db|
    db.vm.box="Ubuntu_Server_20_04_LTS"
    db.vm.hostname = "db.mario.lab"
    db.vm.network "private_network", ip: "192.168.89.101"
    db.vm.synced_folder "application/db/", "/synced"
    db.vm.provision "shell", path: "db.sh"
  end

end
