---
- name: Setup /etc/hosts
  hosts: all
  tasks:
    - name: Insert docker to etc hosts
      lineinfile:
        path: /etc/hosts
        line: 192.168.99.100 docker.dof.lab docker
      become: yes
