all:
  hosts:
    node-1:
    node-2:
  children:
    servers:
      hosts:
        node-1:
        node-2:
    docker_manager:
      hosts:
        node-1:
    docker_worker:
      hosts:
        node-2:
    jenkins:
      hosts:
        node-1: