all:
  hosts:
    master:
      ansible_host: 10.1.1.2
    slave:
      ansible_host: 10.1.1.3
  children:
    servers:
      hosts:
        master:
        slave:
    swarm_initial:
      hosts:
        master:
    swarm_additional:
      hosts:
        slave:
    jenkins:
      hosts:
        master:
