all:
  hosts:
    node-1:
    node-2:
  children:
    servers:
      hosts:
        node-1:
        node-2:
    jenkins_master:
      hosts:
        node-1:
    jenkins_slave:
      hosts:
        node-2:
    docker_host:
      hosts:
        node-1:
        node-2:
    docker_swarm_init:
      hosts:
        node-1:
    docker_swarm_join_worker:
      hosts:
        node-2: