- name: Build and Push jenkins Image
  docker_image:
    build:
      path: /sync/jenkins
    name: jenkins-docker
    repository: 192.168.201.120:5000/jenkins
    push: yes
    source: build

- name: Create jenkins docker network
  docker_network:
    name: jenkins

- name: Run Jenkins container
  docker_container:
    name: jenkins-docker-run
    image: 192.168.201.120:5000/jenkins/jenkins-docker
    pull: yes

# From https://www.jenkins.io/doc/book/installing/docker/
# docker run \
#   --name jenkins-docker \
#   --rm \
#   --detach \
#   --privileged \
#   --network jenkins \
#   --network-alias docker \
#   --env DOCKER_TLS_CERTDIR=/certs \
#   --volume jenkins-docker-certs:/certs/client \
#   --volume jenkins-data:/var/jenkins_home \
#   --publish 2376:2376 \
#   docker:dind \
#   --storage-driver overlay2