# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false

  config.vm.define "consul" do |consul|
    consul.vm.box="shekeriev/centos-8-minimal"
    consul.vm.hostname = "consul.dof.lab"
    consul.vm.network "private_network", ip: "192.168.99.100"
    consul.vm.network "forwarded_port", guest: 8500, host: 8500, auto_correct: true
    consul.vm.network "forwarded_port", guest: 8600, host: 8600, auto_correct: true
    consul.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
    consul.vm.provision "shell", inline: <<EOS
echo "* Add hosts ..."
echo "192.168.99.100 consul.dof.lab consul" >> /etc/hosts

echo "* Install BASH Completion, etc. ..."
dnf install -y bash-completion jq unzip bind-utils socat nc

echo "* Firewall - open port 8500 and 8600 ..."
firewall-cmd --add-port=8500/tcp --permanent
firewall-cmd --add-port=8600/tcp --permanent

echo "* Firewall - reload rules ..."
firewall-cmd --reload

EOS
  end

end
