- name: Insert dob-db entry to etc hosts
  lineinfile:
    path: /etc/hosts
    line: 10.1.1.3 dob-db

- name: Install nginx
  apt:
    name: nginx
    state: latest
    install_recommends: yes
    update_cache: yes

- name: Install php
  apt:
    name: php
    state: latest
    install_recommends: yes

- name: Install php-fpm
  apt:
    name: php-fpm
    state: latest
    install_recommends: yes

- name: Install php-mysql
  apt:
    name: php-mysql
    state: latest
    install_recommends: yes

- name: Copy nginx site config
  copy:
    src: /sync/config/bulgaria.conf
    dest: /etc/nginx/sites-available

- name: Remove default site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Create a symbolic link for site config
  ansible.builtin.file:
    src: /etc/nginx/sites-available/bulgaria.conf
    dest: /etc/nginx/sites-enabled/bulgaria.conf
    owner: root
    group: root
    state: link

- name: Copy website
  copy:
    src: /sync/web
    dest: /var/www

- name: Restart NGINX
  systemd:
    name: nginx
    state: restarted