apiVersion: v1
kind: Service
metadata:
  name: hw-web-svc
  labels:
    app: hw-web
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: hw-web
