all:
  hosts:
    node-1:
    node-2:
    node-3:
  children:
    servers:
      hosts:
        node-1:
        node-2:
        node-3:
    nagios_monitor:
      hosts:
        node-1:
    nagios_monitored:
      hosts:
        node-2:
        node-3:
    jenkins_master:
      hosts: 
        node-1:
    jenkins_slave:
      hosts:
        node-2:
        node-3:
    docker_host:
      hosts:
        node-1:
        node-2:
        node-3:
    docker_swarm_init:
      hosts:
        node-1:
    docker_swarm_worker:
      hosts:
        node-2:
        node-3: