all:
  hosts:
    ansible_host:
      ansible_connection: local
  children:
    servers:
      hosts:
        database:
          ansible_host: 10.1.1.3
        webserver:
          ansible_host: 10.1.1.4
    databases:
      hosts:
        database:
    webservers:
      hosts:
        webserver: