# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = "alpine_docker_box"
  
  config.vm.provider :virtualbox do |vbox|
    vbox.customize ["modifyvm", :id, "--memory", "768"]
  end
  
  config.vm.synced_folder "sync", "/sync"
  config.vm.provision "shell", path: "provision.sh"

  (1..3).each do |i|
    config.vm.define "dh-#{i}" do |node|
      node.vm.hostname = "dh-#{i}.mario.lab"
      node.vm.network "private_network",
        name: "vboxnet0",
        ip: "10.1.1.#{1+i}",
        netmask: "24"
      node.vm.network "forwarded_port",
        guest: 2376, 
        host: 2375+i, 
        auto_correct: true
      node.vm.network "forwarded_port",
        guest: 8080, 
        host: 8080+i, 
        auto_correct: true
      if i == 1
        node.vm.network "forwarded_port",
          guest: 5000, 
          host: 5000, 
          auto_correct: true
        node.vm.network "public_network",
          ip: "192.168.201.120",
          bridge: "enp0s31f6"
      end
    end
  end

end
