# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.box = "alpine_docker_box"
  config.vm.synced_folder "sync", "/sync"
  config.vm.provision "shell", path: "provision.sh"
  (1..2).each do |i|
    config.vm.define "dh#{i}" do |node|
      node.vm.hostname = "dh#{i}.mario.lab"
      node.vm.network "private_network", name: "vboxnet0", ip: "10.1.1.#{1+i}", netmask: "24"
      node.vm.network "forwarded_port", guest: 2376, host: 2375+i, auto_correct: true
    end
  end
end
