- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present

- name: Add Jenkins Repo
  shell: echo "deb https://pkg.jenkins.io/debian-stable binary/" | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/jenkins.list

- name: Install openjdk
  apt:
    name: openjdk-11-jdk
    state: latest
    install_recommends: yes
    update_cache: yes

- name: Install jenkins
  apt:
    name: jenkins
    state: latest
    install_recommends: yes

- name: Stop jenkins
  systemd:
    name: jenkins
    daemon-reload: yes
    state: stopped

- name: Prep jenkis user
  user:
    name: jenkins
    password: "$6$ZeC81LPp1JnSJFTX$Zgu32enarP/gzIBNaUCHcbcyHAx.CoCo/F0fSos32hUOMPzs0Q9vqSeMke5ahXU9X13A.hGO08eobxysoK57P1"
    append: yes
    groups: sudo
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    shell: /bin/bash

- name: Set jenkins user as sudoer
  copy:
    content: 'jenkins ALL=(ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/jenkins
    owner: root
    group: root
    mode: 0440

# - name: Copy jenkins
#   become: yes
#   copy:
#     src: /sync/var/lib/jenkins/
#     dest: /var/lib/jenkins/
#     owner: jenkins
#     group: jenkins

# - name: Copy jenkins config
#   become: yes
#   copy:
#     src: /sync/var/lib/jenkins/config.xml
#     dest: /var/lib/jenkins/config.xml
#     owner: jenkins
#     group: jenkins

# - name: Copy jenkins credentials
#   become: yes
#   copy:
#     src: /sync/var/lib/jenkins/credentials.xml
#     dest: /var/lib/jenkins/credentials.xml
#     owner: jenkins
#     group: jenkins

# - name: Copy jenkins jobs
#   become: yes
#   copy:
#     src: /sync/var/lib/jenkins/jobs/
#     dest: /var/lib/jenkins/jobs/
#     owner: jenkins
#     group: jenkins

# - name: Copy jenkins nodes
#   become: yes
#   copy:
#     src: /sync/var/lib/jenkins/nodes/
#     dest: /var/lib/jenkins/nodes/
#     owner: jenkins
#     group: jenkins

# - name: Copy jenkins plugins
#   become: yes
#   copy:
#     src: /sync/var/lib/jenkins/plugins/
#     dest: /var/lib/jenkins/plugins/
#     owner: jenkins
#     group: jenkins

# - name: Copy jenkins secrets
#   become: yes
#   copy:
#     src: /sync/var/lib/jenkins/secrets/
#     dest: /var/lib/jenkins/secrets/
#     owner: jenkins
#     group: jenkins

# - name: Copy jenkins users
#   become: yes
#   copy:
#     src: /sync/var/lib/jenkins/users/
#     dest: /var/lib/jenkins/users/
#     owner: jenkins
#     group: jenkins

- name: Copy jenkins
  shell: rsync -r /sync/var/lib/jenkins /var/lib > /sync/sync_result.out
  args:
    creates: /sync/sync_result.out

- name: Set ownership jenkins
  file:
    path: /var/lib/jenkins
    state: directory
    recurse: yes
    owner: jenkins
    group: jenkins

- name: Copy jenkins initial admin password
  shell: sudo cp /var/lib/jenkins/secrets/initialAdminPassword /sync/initialAdminPassword
  args:
    creates: /sync/initialAdminPassword

- name: Start jenkins
  systemd:
    name: jenkins
    state: started

# TODO
# Auto setup 
# Copy jenkins ssh key to localhost
