apiVersion: apps/v1
kind: Deployment
metadata:
  name: appa-deploy
spec:
  replicas: 10
  selector:
    matchLabels: 
      app: appa
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: appa
    spec:
      containers:
      - name: appa-container
        image: shekeriev/k8s-appa:v1
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: appa-svc
  labels:
    app: appa
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: appa
