---
- name: Setup node-1
  hosts: node-1
  tasks:
    - name: Insert slave entry to etc hosts
      lineinfile:
        path: /etc/hosts
        line: 10.1.1.3 node-2
      become: yes

- name: Setup node-1
  hosts: node-1
  tasks:
    - name: Insert slave entry to etc hosts
      lineinfile:
        path: /etc/hosts
        line: 10.1.1.4 node-3
      become: yes

- name: Setup node-2
  hosts: node-2
  tasks:
    - name: Insert master entry to etc hosts
      lineinfile:
        path: /etc/hosts
        line: 10.1.1.2 node-1
      become: yes

- name: Setup node-2
  hosts: node-2
  tasks:
    - name: Insert master entry to etc hosts
      lineinfile:
        path: /etc/hosts
        line: 10.1.1.4 node-3
      become: yes

- name: Setup node-3
  hosts: node-3
  tasks:
    - name: Insert master entry to etc hosts
      lineinfile:
        path: /etc/hosts
        line: 10.1.1.2 node-1
      become: yes

- name: Setup node-3
  hosts: node-3
  tasks:
    - name: Insert master entry to etc hosts
      lineinfile:
        path: /etc/hosts
        line: 10.1.1.3 node-2
      become: yes

# This is garbage