apiVersion: v1
kind: Pod
metadata:
  name: mongo-db
  labels:
    app: mongo-db
spec:
  containers:
  - name: mongo-db
    image: mongo
    env:
    - name: MONGO_INITDB_ROOT_USERNAME 
      value: root
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: example
    - name: MONGO_INITDB_DATABASE
      value: monogodb
    ports:
    - containerPort: 27017

---

apiVersion: v1
kind: Pod
metadata:
  name: mongo-ui
  labels:
    app: mongo-ui
spec:
  containers:
  - name: mongo-ui
    image: mongo-express
    env:
    - name: ME_CONFIG_MONGODB_SERVER 
      value: mongo-db
    - name: ME_CONFIG_MONGODB_ADMINUSERNAME 
      value: root
    - name: ME_CONFIG_MONGODB_ADMINPASSWORD
      value: example
    ports:
    - containerPort: 8081