apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  labels:
    app: mongo-db
spec: 
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo-db

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-ui
  labels:
    app: mongo-ui
spec:
  type: NodePort 
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: mongo-ui
