- name: Install Docker
  apt:
    name: docker
    state: latest
    install_recommends: yes
    update_cache: yes

- name: Install Docker SDK for Python
  pip:
    name: docker
    state: latest
    executable: pip3

- name: Add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: yes

# - name: Fix docker daemon config

# - name: Restart docker daemon