- name: Add Docker repo key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg
    warn: false

- name: Add Docker Repo
  shell: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: Install docker-ce
  apt:
    name: docker-ce
    state: latest
    install_recommends: yes
    update_cache: yes

- name: Install docker-ce-cli
  apt:
    name: docker-ce-cli
    state: latest
    install_recommends: yes

- name: Install containerd.io
  apt:
    name: containerd.io
    state: latest
    install_recommends: yes

- name: Install Docker SDK for Python
  pip:
    name: docker
    state: latest
    executable: pip3

- name: Add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: yes

- name: Copy docker daemon config
  copy:
    src: /sync/etc/docker/daemon.json
    dest: /etc/docker/daemon.json

- name: Create a directory if it does not exist
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory

- name: Copy docker daemon unit override
  copy:
    src: /sync/etc/systemd/system/docker.service.d/override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf

- name: Restart Docker Daemon
  systemd:
    name: docker
    daemon-reload: yes
    state: restarted

- name: create remote context
  shell: docker context create --docker host=tcp://localhost:2375 remote && docker context use remote > ~/.docker-is-remote
  args:
    creates: ~/.docker-is-remote