- name: Add Docker repo key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg
    warn: false

- name: Add Docker Repo
  shell: echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/docker.list

- name: Install docker-ce
  apt:
    name: docker-ce
    state: latest
    install_recommends: yes
    update_cache: yes

- name: Install docker-ce-cli
  apt:
    name: docker-ce-cli
    state: latest
    install_recommends: yes
    update_cache: yes

- name: Install containerd.io
  apt:
    name: containerd.io
    state: latest
    install_recommends: yes
    update_cache: yes

- name: Install Docker SDK for Python
  pip:
    name: docker
    state: latest
    executable: pip3

- name: Add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: yes

- name: Copy docker daemon config
  copy:
    src: /sync/etc/docker/daemon.json
    dest: /etc/docker/daemon.json

# - name: Restart Docker Daemon
#   systemd:
#     name: 
#     state: restarted