- name: Docker Swarm Init
  import_tasks: docker_swarm_init.yml
  when: ansible_os_family == 'Debian'

- name: Create Docker Context
  import_tasks: docker_context_create_remote.yml

- name: Create Docker Registry Service
  import_tasks: docker_service_create_registry.yml