---
- name: Setup Master
  hosts: master
  tasks:
    - name: Insert slave entry to etc hosts
      lineinfile:
        path: /etc/hosts
        line: 10.1.1.3 slave

- name: Setup Slave
  hosts: slave
  tasks:
    - name: Insert master entry to etc hosts
      lineinfile:
        path: /etc/hosts
        line: 10.1.1.2 master

- hosts: servers
  roles:
    - servers
