---
- hosts: servers
  roles:
    - servers

# - name: Setup node-1
#   hosts: node-1
#   tasks:
#     - name: Insert slave entry to etc hosts
#       lineinfile:
#         path: /etc/hosts
#         line: 10.1.1.3 node-2
    # - name: Remove a swarm manager
    #   docker_swarm:
    #     state: absent
    #     force: true
    # - name: Init a new swarm with default parameters
    #   docker_swarm:
    #     advertise_addr: 10.1.1.2
    #     state: present
    #   register: swarm_init_result
    # - name: Show swarm init result
    #   debug:
    #     var: swarm_init_result
    # - name: Save swarm init reuslt
    #   copy:
    #     content: "{{ swarm_init_result }}"
    #     dest: /sync/SwarmInit.json

# - name: Setup node-2
#   hosts: node-2
#   tasks:
#     - name: Insert master entry to etc hosts
#       lineinfile:
#         path: /etc/hosts
#         line: 10.1.1.2 node-1
    # - name: Load swarm_init_result
    #   include_vars:
    #     file: /sync/SwarmInit.json
    #     name: swarm_init_result
    # - name: Show swarm init result
    #   debug:
    #     var: swarm_init_result.swarm_facts.JoinTokens.Manager
    # - name: Join swarm as manager
    #   docker_swarm:
    #     advertise_addr: 10.1.1.3
    #     state: join
    #     join_token: swarm_init_result.swarm_facts.JoinTokens.Manager
    #     remote_addrs: [ '10.1.1.2:2377' ]

# TASK [Show swarm init result] **************************************************
# ok: [master] => {
#     "swarm_init_result": {
#         "actions": [
#             "New Swarm cluster created: o8wlxxk0z3fb5d3rjunsa11xa"
#         ],
#         "changed": true,
#         "failed": false,
#         "result": "",
#         "swarm_facts": {
#             "JoinTokens": {
#                 "Manager": "SWMTKN-1-476bxxfnjvv3obsmsjwr4bub8o5rvrzbrjbjr2j5c31h6khhcl-dpjbzy6q73kxmdruiczsbh2jl",
#                 "Worker": "SWMTKN-1-476bxxfnjvv3obsmsjwr4bub8o5rvrzbrjbjr2j5c31h6khhcl-4b4se1e4pqmpca0h79reb6mcl"
#             },
#             "UnlockKey": null
#         }
#     }
# }
