apiVersion: apps/v1
kind: Deployment
metadata:
  name: environment-variables
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: environment-variables
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: environment-variables
    spec:
      containers:
      - name: softunit-container
        image: shekeriev/environment
        env:
        - name: CONT_ENV_VAR
          value: Kubernetes-Demo
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: environment-variables-svc
  labels:
    app: environment-variables
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30005
    protocol: TCP
  selector:
    app: environment-variables
