- name: Install Python apt package
  pip:
    name: python-apt
    state: latest
    executable: pip3

- name: Install packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: latest
    install_recommends: yes
    update_cache: yes
  become: yes

- name: Stop multipathd.socket
  systemd:
    name: multipathd.socket
    state: stopped
    enabled: no
  become: yes

- name: Stop multipathd
  systemd:
    name: multipathd
    state: stopped
    enabled: no
  become: yes