FROM docker.elastic.co/elasticsearch/elasticsearch:7.14.1

ENV xpack.security.enabled false
ENV xpack.watcher.enabled false
ENV xpack.graph.enabled false
ENV xpack.monitoring.enabled false
ENV http.host 0.0.0.0
ENV transport.host 127.0.0.1
