# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false

  config.vm.define "web" do |web|
    web.vm.box = "shekeriev/centos-8-minimal"
    web.vm.hostname = "dob-web.dob.lab"
    web.vm.network "private_network", ip: "192.168.99.100"
    web.vm.network "forwarded_port", guest: 80, host: 8000
    
    web.vm.synced_folder "web/", "/vagrant"

    web.vm.provision "ansible_local" do |ansible|
      ansible.become = true
      ansible.install_mode = :default
      ansible.playbook = "playbook.yml"
    end

  end
  
  config.vm.define "db" do |db|
    db.vm.box = "shekeriev/ubuntu-20-04-server"
    db.vm.hostname = "dob-db.dob.lab"
    db.vm.network "private_network", ip: "192.168.99.101"
    
    db.vm.synced_folder "db/", "/vagrant"

    db.vm.provision "shell", inline: <<EOS
echo "* Disable auto-update timers and service if present ..."
systemctl disable --now apt-daily-upgrade.timer &> /dev/null || true
systemctl disable --now apt-daily.timer &> /dev/null || true
systemctl disable --now unattended-upgrades.service &> /dev/null || true
sed -i s/1/0/g /etc/apt/apt.conf.d/20auto-upgrades || true
EOS
    
    db.vm.provision "ansible_local" do |ansible|
      ansible.become = true
      ansible.install_mode = :default
      ansible.playbook = "playbook.yml"
      ansible.galaxy_role_file = "requirements.yml"
      ansible.galaxy_roles_path = "/etc/ansible/roles"
      ansible.galaxy_command = "sudo ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path} --force"
    end

  end

end
