# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  $puppet = <<PUPPET
    sudo dnf install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
    sudo dnf install -y puppet
PUPPET

  $modules = <<MODULES
    puppet module install puppetlabs/mysql
    puppet module install puppetlabs-firewall
    sudo cp -vR ~/.puppetlabs/etc/code/modules/ /etc/puppetlabs/code/
MODULES

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.box = "shekeriev/centos-8-minimal"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.provision "shell", inline: $puppet, privileged: false

  config.vm.define 'web' do |web|
    web.vm.hostname = 'web'
    web.vm.network 'private_network', ip: '192.168.50.2'
    web.vm.provision "shell", inline: $modules, privileged: false
    web.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file = "web.pp"
      puppet.options = "--verbose --debug"
    end
  end

  config.vm.define 'db' do |db|
    db.vm.hostname = 'db'
    db.vm.network 'private_network', ip: '192.168.50.3'
    db.vm.provision "shell", inline: $modules, privileged: false
    db.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file = "db.pp"
      puppet.options = "--verbose --debug"
    end
  end

end
