---
  - name: Install EPEL Repository
    dnf:
      name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      state=present
      disable_gpg_check=yes
  - name: Install NRPE
    dnf:
      name=nrpe,nagios-plugins-nrpe,nagios-plugins-all
      enablerepo=codeready-builder-for-rhel-8-rhui-rpms
      state=present
  - name: Substitute nrpe.cfg
    copy:
      src=/vagrant/nagios/nrpe.cfg
      dest=/etc/nagios/nrpe.cfg
  - name: Add nrpe to sudoers.d
    copy:
      src=/vagrant/nagios/nrpe.sudo
      dest=/etc/sudoers.d/nrpe
  - name: Add nagios to sudoers.d
    copy:
      src=/vagrant/nagios/nagios.sudo
      dest=/etc/sudoers.d/nagios
  - name: Adding user ec2-user to docker group  
    user: name=ec2-user
      groups=docker
      append=yes
  - name: Adding user nrpe to docker group  
    user: name=nrpe
      groups=docker
      append=yes
  - name: Adding user nagios to docker group  
    user: name=nagios
      groups=docker
      append=yes
  - name: Copy additional docker plugin
    copy:
      src=/vagrant/nagios/check_docker_container.sh
      dest=/usr/lib64/nagios/plugins/check_docker_container.sh
  - name: Turn on execute permission for check_docker_container.sh
    file:
      path=/usr/lib64/nagios/plugins/check_docker_container.sh
      mode="a+x"
  - name: Enable and start NRPE
    service:
      name=nrpe
      state=started
      enabled=true
