- name: Load swarm_init_result
  include_vars:
    file: /sync/SwarmInit.json
    name: swarm_init_result

- name: Show swarm init result
  debug:
    var: swarm_init_result.swarm_facts.JoinTokens.Worker

- name: Join swarm as Worker
  docker_swarm:
    advertise_addr: 10.1.1.3
    state: join
    join_token: "{{ swarm_init_result.swarm_facts.JoinTokens.Worker }}"
    remote_addrs: [ '10.1.1.2:2377' ]