- name: Load swarm_init_result
  include_vars:
    file: /sync/SwarmInit.json
    name: swarm_init_result

- name: Show swarm init result
  debug:
    var: swarm_init_result.swarm_facts.JoinTokens.Worker

- name: Join swarm as Worker
  docker_swarm:
    advertise_addr: 10.1.1.3
    state: join
    join_token: "{{ swarm_init_result.swarm_facts.JoinTokens.Worker }}"
    remote_addrs: [ '10.1.1.2:2377' ]

- name: create remote context
  shell: |
    docker context create --docker host=tcp://10.1.1.2:2375 remote
    docker context use remote
    touch .docker-is-remote
  args:
    chdir: /home/vagrant/
    creates: .docker-is-remote