# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.vm.box = "generic/ubuntu2104"

  config.vm.provider :virtualbox do |config_vbox|
    config_vbox.customize ["modifyvm", :id, "--memory", "2048"]
  end

  config.vm.define "docker" do |node|
    node.vm.hostname = "docker.dof.lab"
    node.vm.network "private_network", ip: "192.168.99.100"
    node.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true # HTTP-ALT
    node.vm.network "forwarded_port", guest: 2375, host: 2375, auto_correct: true # DOCKER
    node.vm.synced_folder "sync", "/sync"
    node.vm.provision "shell", path: "provision.sh"
    node.vm.provision "shell", path: "provision_ansible.sh"
  end

end
