Vagrant.configure("2") do |config|
  config.vm.box = "shekeriev/centos-8-minimal"

  config.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
end
