# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  # Chef Server - CentOS 8.x
  config.vm.define "server" do |server|
    server.vm.box = "shekeriev/centos-8-minimal"
    server.vm.hostname = "chef-server"
    server.vm.network "private_network", ip: "192.168.99.100"
    server.vm.provision "shell", path: "add_hosts.sh"

    server.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 4096
      v.cpus = 1
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  end
  
  # Chef Client #1 - CentOS 8.x
  config.vm.define "client1" do |client1|
    client1.vm.box = "shekeriev/centos-8-minimal"
    client1.vm.hostname = "chef-client-1"
    client1.vm.network "private_network", ip: "192.168.99.101"
    client1.vm.provision "shell", path: "add_hosts.sh"

    client1.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 512
      v.cpus = 1
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  end

  # Chef Client #2 - Ubuntu 20.04 LTS
  config.vm.define "client2" do |client2|
    client2.vm.box = "shekeriev/ubuntu-20-04-server"
    client2.vm.hostname = "chef-client-2"
    client2.vm.network "private_network", ip: "192.168.99.102"
    client2.vm.provision "shell", path: "add_hosts.sh"

    client2.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 512
      v.cpus = 1
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  end
  
  # Chef DK - CentOS 8.x
  config.vm.define "workstation" do |workstation|
    workstation.vm.box = "shekeriev/centos-8-minimal"
    workstation.vm.hostname = "chef-dk"
    workstation.vm.network "private_network", ip: "192.168.99.105"
    workstation.vm.provision "shell", path: "add_hosts.sh"

    workstation.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 2048
      v.cpus = 1
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  end
  
end
