apiVersion: v1
kind: Pod
metadata:
  name: volume-pod-gitrepo
  labels:
    app: volume-pod-gitrepo
spec:
  containers:
  - image: nginx
    name: web
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: html
    gitRepo:
      repository: https://github.com/shekeriev/simple-html-page.git
      revision: master
      directory: .
---
apiVersion: v1
kind: Service
metadata:
  name: volume-pod-gitrepo-svc
  labels:
    app: volume-pod-gitrepo
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30005
    protocol: TCP
  selector:
    app: volume-pod-gitrepo
