apiVersion: v1
kind: Pod
metadata:
  name: volume-pod-emptydir
  labels:
    app: volume-pod-emptydir
spec:
  containers:
  - image: shekeriev/www-date
    name: generator
    volumeMounts:
    - name: www
      mountPath: /var/www-data
  - image: nginx
    name: consumer
    volumeMounts:
    - name: www
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: www
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: volume-pod-emptydir-svc
  labels:
    app: volume-pod-emptydir
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30005
    protocol: TCP
  selector:
    app: volume-pod-emptydir
