- name: Docker Service Create Registry
  docker_swarm_service:
    name: registry
    image: registry:latest
    publish:
      - published_port: 5000
        target_port: 5000
  register: registry_create_result

- name: Show registry create result
  debug:
    var: swarm_init_result

- name: Save registry create result
  copy:
    content: "{{ registry_create_result }}"
    dest: /sync/registry_create_result.json